### ISSUE TITLE
Write a script to mass-download QPs from library

### ISSUE THREAD

**Issue by athityakumar** [metakgp/mfqp-source#15]
For example, library site went down yesterday & there were a lot of messages in metakgp's message box regarding this. If the QPs are all kept in metakgp's G-drive, then we wouldn't rely much on library site.

**Comment by icyflame** [comment]
Also, this script will intelligently rename the papers as per the convention mentioned [here](https://github.com/metakgp/mfqp-source/blob/master/scripts/upload/upload.rb#L17-L19).

**Comment by icyflame** [comment]
A simple `wget -mr http://10.32.17.9` does it. No script required!

**Comment by athityakumar** [comment]
But the script doesn't also add the papers into json file right? Maybe we could club the wget and inserting into json together?

**Comment by icyflame** [comment]
@athityakumar Adding to JSON can be done by that other script. But I wrote the script to add to JSON. check `mfqp-source/scripts/`

**Comment by athityakumar** [comment]
@icyflame : Oops, sorry. I didn't see the 4 new scripts there. Peace! :smile:
