### ISSUE TITLE
Allow direct upload?

### ISSUE THREAD

**Issue by vivekiitkgp** [metakgp/mfqp-source#4]
Currently, I feel it is a bit inconvenient to send papers via mail.

**Comment by amrav** [comment]
Do you have a proposal for a better solution, that will allow us to do reviews? Why is mail inconvenient?

**Comment by vivekiitkgp** [comment]
The online upload can still allow us to do reviews. Also, with online one will be able to do batch upload easily. Right now, I am having to send one mail per paper. If I am missing out on some other way, do let me know.

Otherwise, direct upload will be a good to have thing.

**Comment by amrav** [comment]
We figured that most people will upload from their mobile, and sending multiple emails is not that much more work than multiple uploads. However, it will take us some effort to build an upload interface, and a review interface for those uploads. Email gives us all these benefits for free. It's not ideal, but it's 1% of the effort for 90% of the gain.

**Comment by vivekiitkgp** [comment]
Of course. There's no hurry to work on this.

**Comment by icyflame** [comment]
One more thing that me, @amrav and @nuwandavek discussed right at the beginning was that the barrier to entry has to be kept at the bare minimum, only then people will be able to quickly contribute.

> But we figured that unless the barrier for people to post is extremely low, it might not be very 
> successful.
> Maybe click a photo and whatsapp it to a number?

These were @nuwandavek 's exact words. So, using Mail goes in that direction.
